apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.deployment.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: {{ .Values.deployment.name }}