apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-reporting-farmer-staging
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-dev-alerts
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-dev-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-dev-alerts
spec:
  destination:
    namespace: cf-reporting-staging
    server: https://kubernetes.default.svc
  source:
    path: argocd/dev/helm-charts/cf-reporting-farmer
    repoURL: https://github.com/DimitraAgTech/devops
    targetRevision: main
    helm:
      valueFiles:
        - staging-values.yaml
  project: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true