apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-reporting-farmer-dev
  namespace: argo
spec:
  destination:
    namespace: cf-reporting-dev
    server: https://kubernetes.default.svc
  source:
    path: argocd/dev/helm-charts/cf-reporting-farmer
    repoURL: https://github.com/DimitraAgTech/devops
    targetRevision: main
    helm:
      valueFiles:
        - dev-values.yaml
  project: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true